### ISSUE TITLE
conda - cuda + pytorch out of date

### ISSUE THREAD

**Issue by johndpope** [williamyang1991/DualStyleGAN#1]
inetune_dualstylegan.py  pretrain_dualstylegan.py
(dualstylegan_env) ➜  DualStyleGAN git:(main) ✗         python style_transfer.py 
/home/jp/miniconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

**Comment by johndpope** [comment]
torch should go to
1.9.0+cu111

**Comment by williamyang1991** [comment]
Yes, my cuda is 10.1 so I install pytorch 1.7.1.
You should install pytorch that matches your cuda version.
I will add this info in the Readme.

**Comment by johndpope** [comment]
thx
