### ISSUE TITLE
加载预训练模型出错

### ISSUE THREAD

**Issue by Xia-zx** [williamyang1991/DualStyleGAN#104]
<img width="709" alt="微信图片_20240529185822" src="https://github.com/williamyang1991/DualStyleGAN/assets/40895291/0d577d6b-8188-42e9-b855-ec0e7e017f88">

<img width="161" alt="1" src="https://github.com/williamyang1991/DualStyleGAN/assets/40895291/f3c0d96b-0eb8-469a-885e-b27842960f08">
<img width="587" alt="2" src="https://github.com/williamyang1991/DualStyleGAN/assets/40895291/930ed681-f8c1-43af-805a-ceaa619168e5">

什么原因，求助

**Comment by williamyang1991** [comment]
你提供的信息过少，我没法帮你

**Comment by Xia-zx** [comment]
> 你提供的信息过少，我没法帮你

我按照readme中说的，下载了cartoon的generator.pt按照要求目录存放，运行python style_transfer.py ，在76行generator.load_state_dict(ckpt["g_ema"])，出现报错

**Comment by williamyang1991** [comment]
至少提供你输入的命令行吧

**Comment by Xia-zx** [comment]
> python style_transfer.py

完全按照readme中说的，命令行就是python style_transfer.py ，没提供参数

**Comment by williamyang1991** [comment]
那我只能猜测你模型下载错了
你可以试着下载一下其他风格的，比如caricature，然后运行一下
```
python style_transfer.py --style caricature --name caricature_transfer --style_id 0 --weight 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
```
看是不是报一样的错。
如果没报错就是你下载的有问题
如果也报错，那可能是代码哪里有问题（但是那么多人都试过了一直都没啥问题），你可以试一下添加
```
generator.load_state_dict(ckpt["g_ema"], strict=False)
```
去忽略那些unexpected key

**Comment by Xia-zx** [comment]
> 那我只能猜测你模型下载错了 你可以试着下载一下其他风格的，比如caricature，然后运行一下
> 
> ```
> python style_transfer.py --style caricature --name caricature_transfer --style_id 0 --weight 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
> ```
> 
> 看是不是报一样的错。 如果没报错就是你下载的有问题 如果也报错，那可能是代码哪里有问题（但是那么多人都试过了一直都没啥问题），你可以试一下添加
> 
> ```
> generator.load_state_dict(ckpt["g_ema"], strict=False)
> ```
> 
> 去忽略那些unexpected key

添加
```
generator.load_state_dict(ckpt["g_ema"], strict=False)
``` 
后就好了，感谢帮助
