### ISSUE TITLE
How to achieve toon style results like ToonApp

### ISSUE THREAD

**Issue by dummyuser-123** [williamyang1991/DualStyleGAN#106]
Hello @williamyang1991, 

First of all, thanks for this great work. It successfully transforms any face image into a cartoon style. However, I have some questions about training custom styles using DualStyleGAN. I want to generate results like the ones shown below:

<table>
  <tr>
    <td><strong>Input Image:</strong></td>
    <td><strong>Output Image:</strong></td>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/be02ccf1-5526-4da0-8a4d-8125bfddb490" alt="Input Image" width="300"></td>
    <td><img src="https://github.com/user-attachments/assets/48361c59-0cf7-41a8-83dd-2532cda3a7fd" alt="Output Image" width="300"></td>
  </tr>
</table>

1. How can I generate such accurate results? Specifically, how can I ensure that the background, clothing details, and surroundings remain the same as in the input image while applying the cartoon style?
2. How can the model cartoonize other parts of the image (apart from the face) so perfectly?

It would be great if you could share some insights and experiences related to this problem and explain how I can achieve similar results. I have researched various models for image cartoonization and style transfer but have not found a solution.

**Comment by williamyang1991** [comment]
I have no idea the implementation details of ToonApp. 
It's a commercial app, which is out of my domain.

And in your case, you face image is not cropped and aligned. So you may refer to our another work [VToonify](https://github.com/williamyang1991/VToonify), which is more suitable for your case.

And you need to collect the dataset and train dualstylegan and then train vtoonify. But I'm nor sure if VToonify can achieve the same effects as the ToonApp.
