### ISSUE TITLE
Do not change the shape of the face

### ISSUE THREAD

**Issue by GrigorySamokhin** [williamyang1991/DualStyleGAN#12]
Hello! Can you tell me if there is some way to configure the inference so that it does not change the shape of the face as in the photo below?
![Unknown_input](https://user-images.githubusercontent.com/47357694/161095226-c178246f-dcc5-4987-b8c5-f27a4d349f3d.jpg)
<img width="482" alt="Screenshot 2022-03-31 at 18 42 01" src="https://user-images.githubusercontent.com/47357694/161095317-9f7466c8-e10d-43f4-8416-746cb565f0eb.png">

**Comment by williamyang1991** [comment]
You can try different interp_weights to find the ideal results, for example, using [0]*7+[1.0]*11 for color transfer only.

Please refer to the Section  **Navigation with different interp_weights to achieve flexible style manipulation** of the [notebook](https://github.com/williamyang1991/DualStyleGAN/blob/main/notebooks/inference_playground.ipynb)

**Comment by GrigorySamokhin** [comment]
Thanks you a lot!
