### ISSUE TITLE
creating environment failed

### ISSUE THREAD

**Issue by nicolai256** [williamyang1991/DualStyleGAN#13]
(base) PS C:\deepdream-test\DualStyleGAN> conda env create -f ./environment/dualstylegan_env.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ca-certificates==2022.2.1=h06a4308_0
  - libgcc-ng==9.3.0=h2828fa1_19
  - faiss==1.7.1=py38h7b17aaf_0_cpu
  - libedit==3.1.20191231=he28a2e2_2
  - python-lmdb==1.2.1=py38h2531618_1
  - matplotlib-base==3.3.4=py38h62a2d02_0
  - libffi==3.2.1=he1b5a44_1007
  - certifi==2021.10.8=py38h06a4308_2
  - _libgcc_mutex==0.1=conda_forge
  - scikit-image==0.18.1=py38ha9443f7_0
  - libfaiss==1.7.1=hb573701_0_cpu
  - python==3.8.3=cpython_he5300dc_0
  - setuptools==49.6.0=py38h578d9bd_3
  - pytorch==1.7.1=py3.8_cuda10.1.243_cudnn7.6.3_0
  - libstdcxx-ng==9.3.0=h6de172a_19
  - pillow==8.3.1=py38h2c7a002_0

**Comment by nicolai256** [comment]
just installed it manually

**Comment by nonvegetarian** [comment]
hey, i am having the same issue can you help me with it. I'm new and wanna know how you manually installed it
