### ISSUE TITLE
Question about the dataset split

### ISSUE THREAD

**Issue by eveningglow** [williamyang1991/DualStyleGAN#15]
Thank you for your great work!

I have a question about the dataset split for the training and test. For example, the cartoon dataset has 317 images. To my understanding, these 317 images are used in the training and test at the same time. Did I understand correctly?

**Comment by williamyang1991** [comment]
Yes. 
Our goal is to allow users to collect portrait images of their favourite artworks for DualStyleGAN to pastiche. We would like the dataset to be limited to a few hundred images for easy collection. And this dataset serves as both the training set and testing set.
