### ISSUE TITLE
Great work! Could you provide the checkpoint "fintune-000600.pt"?

### ISSUE THREAD

**Issue by lyn-rgb** [williamyang1991/DualStyleGAN#21]
Hi, I want to destylize the cartoon data, however, I can't fine-tune the stylegan due to the lack of GPU servers, could you provide the checkpoint "fintune-000600.pt"? Thanks.

**Comment by williamyang1991** [comment]
Please find fintune-000600.pt [here](https://drive.google.com/file/d/1w7BJDiSw5_ybelv7jL_Jeu1T-oWEWUmH/view?usp=sharing)

**Comment by lyn-rgb** [comment]
> Please find fintune-000600.pt [here](https://drive.google.com/file/d/1w7BJDiSw5_ybelv7jL_Jeu1T-oWEWUmH/view?usp=sharing)

Thanks!
