### ISSUE TITLE
An environmental problem

### ISSUE THREAD

**Issue by lyfv1** [williamyang1991/DualStyleGAN#26]
Hi~ thanks for your amazing work. I try to follow your work but I am currently experiencing some problems.
Based on experience, I guess it should be an environmental problem.
My enviroment:
pytorch - 1.7.1
torchvision - 0.8.2
cuda - 10.1
cudnn - 7605
Hope to get your help. Many Thanks!

Traceback (most recent call last):
File "/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
subprocess.run(
File "/anaconda3/envs/dualstylegan_env/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "style_transfer.py", line 4, in
from util import save_image, load_image
File "./DualStyleGAN-main/util.py", line 10, in
from model.stylegan.op import conv2d_gradfix
File "./DualStyleGAN-main/model/stylegan/op/init.py", line 1, in
from .fused_act import FusedLeakyReLU, fused_leaky_relu
File "./DualStyleGAN-main/model/stylegan/op/fused_act.py", line 11, in
fused = load(
File "/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 986, in load
return _jit_compile(
File "/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1193, in jit_compile
write_ninja_file_and_build_library(
File "/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1297, in _write_ninja_file_and_build_library
_run_ninja_build(
File "/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in run_ninja_build
raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="gcc" -DPYBIND11_STDLIB="libstdcpp" -DPYBIND11_BUILD_ABI="cxxabi1011" -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include/TH -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include/THC -isystem ~/anaconda3/envs/dualstylegan_env/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS -D__CUDA_NO_HALF_CONVERSIONS -D__CUDA_NO_HALF2_OPERATORS --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c ~/DualStyleGAN-main/model/stylegan/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
FAILED: fused_bias_act_kernel.cuda.o
/usr/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="gcc" -DPYBIND11_STDLIB="libstdcpp" -DPYBIND11_BUILD_ABI="cxxabi1011" -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include/TH -isystem ~/anaconda3/envs/dualstylegan_env/lib/python3.8/site-packages/torch/include/THC -isystem ~/anaconda3/envs/dualstylegan_env/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS -D__CUDA_NO_HALF_CONVERSIONS_ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c ~/DualStyleGAN-main/model/stylegan/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
nvcc fatal : Value 'c++14' is not defined for option 'std'
ninja: build stopped: subcommand failed.

**Comment by williamyang1991** [comment]
The problem comes from the [stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch), and you may check its issue page to see if there are solutions.

Another option is to use the CPU compatible code to replace the `stylegan/op` folder as in [stylegan/op_cpu](https://github.com/williamyang1991/DualStyleGAN/blob/main/model/stylegan/op_cpu#readme), which does not requires compiling the code with c++ and can also run on GPU.

**Comment by RRRRRBL** [comment]
> Thank you very much

hi, I have met the same problem, could you tell me how do handle it finally? thanks!

**Comment by RRRRRBL** [comment]
> The problem comes from the [stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch), and you may check its issue page to see if there are solutions.
> 
> Another option is to use the CPU compatible code to replace the `stylegan/op` folder as in [stylegan/op_cpu](https://github.com/williamyang1991/DualStyleGAN/blob/main/model/stylegan/op_cpu#readme), which does not requires compiling the code with c++ and can also run on GPU.

Thanks a lot !
