### ISSUE TITLE
Huge confusion in Reconstructed 

### ISSUE THREAD

**Issue by SJXer** [williamyang1991/DualStyleGAN#27]
Hello, I am very interested in your job.
However, when I tried to use the model you provided, I found that the img_rec is very different from the original image. I don't know whether it is caused by the psp.encoder or the stylegan.generator.
![cartoon_transfer_23_dddd_overview](https://user-images.githubusercontent.com/49390132/167977439-490b197f-89a9-4402-8b93-ff3cd6a9ef9b.jpg)
Especially after using Webdemo, I found that the same input, Reconstructed on webdemo is very good.
![{afb46084-7ab5-4d6a-9098-3b7c472e7848}](https://user-images.githubusercontent.com/49390132/167977465-86bf539e-b76e-4d5b-9418-0e050373d21d.png)
So I have a huge confusion, do I need to retrain my psp.encoder to get a better instyle_code or do I need to do other work to solve the difficulties I am currently encountering.

**Comment by williamyang1991** [comment]
Your face is not well aligned. You may forget the face alignment option `--align_face`
This is my results using 
```
python style_transfer.py --content ./data/content/tmp.jpg --align_face
```
![tmp](https://user-images.githubusercontent.com/18130694/167994291-bec02f05-4962-4e33-a421-a830a93b72b6.jpg)

Please refer to the testing options in the [README.md](https://github.com/williamyang1991/DualStyleGAN#readme)

**Comment by SJXer** [comment]
I tried the method you taught just now, but the result is still not satisfactory.Is this due to a problem with the alignment model?
![cartoon_transfer_23_dddd_overview](https://user-images.githubusercontent.com/49390132/167998289-45c33a2a-8204-44a9-bfac-e39f96708822.jpg)
![cartoon_transfer_53_123456_overview](https://user-images.githubusercontent.com/49390132/167998314-fb1842a6-5907-4c25-b705-6b28d89ad181.jpg)

**Comment by williamyang1991** [comment]
I don't know. 
Your input image in the first column is strange. 
I think it's the probelm of your input image.

**Comment by SJXer** [comment]
The first column of the image should be the original image, or the aligned image.When I use the alignment operation, the result of my first column will look strange.
![{5984ca41-9d20-49e3-a188-443ce78faeac}](https://user-images.githubusercontent.com/49390132/168002500-ecd21a16-fb60-4239-8836-30d62bcd1f16.png)

**Comment by williamyang1991** [comment]
I think it is your image format problem, which leads to the wrong face alignment (I don't think it is the problem of my code, it might related to the image reading, image cropping, face alignment, etc.) 
You can try the image beblow, which I crop from your image.

![tmp](https://user-images.githubusercontent.com/18130694/168002456-a96668ff-4feb-4613-95e9-a635c4463f16.jpg)

**Comment by SJXer** [comment]
The pictures you gave me do show very good results.
So I naturally assumed that the input image would need to be a square image.Or it can only be 256 x 256.
And after a couple of tries, I realized that the problem really was the image format.
But what kind of picture is ok, I still don't understand.
(I've tried 256*256 JPG, 256*256 PNG, 400*400 JPG, and 400*400 PNG with the same problems I mentioned earlier.)
May I ask, how do you deal with the pictures you gave me?

**Comment by williamyang1991** [comment]
I just downloaded your image in your first reply and cropped it to 256\*256 using Paint app of Windows.

Our method supports non 256\*256 inputs. The exmaple image is 1535\*1024
https://github.com/williamyang1991/DualStyleGAN/blob/main/data/content/unsplash-rDEOVtE7vOs.jpg
