### ISSUE TITLE
Two small typos in readme

### ISSUE THREAD

**Issue by lyx0208** [williamyang1991/DualStyleGAN#28]
![飞书20220515-213920](https://user-images.githubusercontent.com/65213004/168475849-843f64cf-8cda-4dea-9232-828b94ef1234.png)

![20220515-213937](https://user-images.githubusercontent.com/65213004/168475868-2314de04-553f-451b-afc0-d2315eadae35.png)

**Comment by williamyang1991** [comment]
Thank you for pointing the typos. I have fixed them!
