### ISSUE TITLE
Is there any code for generating doc_images in your project？

### ISSUE THREAD

**Issue by 3maoyap** [williamyang1991/DualStyleGAN#31]
Need I write one myself？

**Comment by williamyang1991** [comment]
After preparing your dataset and destylize your images to get the intrinsic style codes and extrinsic style codes,

you can load these style codes of your dataset through
https://github.com/williamyang1991/DualStyleGAN/blob/b300a186cecc9f952f30cfc4e15bcc4d8825dee4/finetune_dualstylegan.py#L515-L536

Then you can reconstruct your dataset through
```
for ind in range(instyles.size(0)):
    instyle = instyles[ind].to(device) 
    exstyle = exstyles[ind].to(device) 
    Simg = Simgs[ind].to(device) 
    fake_img, _ = generator(instyle, exstyle, use_res=True, z_plus_latent=True) 
```

The fake_img is the reconstruction result, and the Simg is the original style image.
You can arrange your results to form the images in doc_images.
