### ISSUE TITLE
inference on cpu

### ISSUE THREAD

**Issue by daeyeoplee** [williamyang1991/DualStyleGAN#36]
I followed your document to inference on cpu, but i found a small error

in DualStyleGAN/model/stylegan/op_cpu/conv2d_gradfix.py

it keep gets name error

you forgot to import contextlib!!

Check and Edit please

And thank you for your great work, I really enjoy using it

**Comment by williamyang1991** [comment]
Thank you for finding this issue!
I have fixed it.
