### ISSUE TITLE
Error during learning process

### ISSUE THREAD

**Issue by hw1204** [williamyang1991/DualStyleGAN#38]
I found this error while running finetune_dualstylegan.py in the last step of learning.
I changed it to jpg because I thought the format of the picture might be a problem, but there must be a problem.
I would appreciate it if you could tell me how to solve it.

load model: /content/drive/MyDrive/generator-pretrain.pt
Loading pSp from checkpoint: /content/drive/MyDrive/encoder.pt
Loading ResNet ArcFace
Encoder model successfully loaded!
Traceback (most recent call last):
  File "finetune_dualstylegan.py", line 529, in <module>
    Simg = transform2(Simg).unsqueeze(dim=3)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 67, in __call__
    img = t(img)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 226, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 284, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by williamyang1991** [comment]
> I changed it to jpg because I thought the format of the picture might be a problem, but there must be a problem.

So the error occurs when you use jpg or png?
The code uses mean and std to adjust 3 channels of your data.

> RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

It seems that your data has 4 channels.
```
    transform2 = transforms.Compose(
    [
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5), inplace=True),
    ])     
```


> File "finetune_dualstylegan.py", line 529, in
> Simg = transform2(Simg).unsqueeze(dim=3)

My original code is `Simg = transform2(Simg).unsqueeze(dim=0)` 
Did you make modifications to the code, which leads to the error?

**Comment by hw1204** [comment]
It was originally a png format, but I changed it to jpg, but there is still an error. I tried your original code, but it's the same! Do you think the png format is a problem?

**Comment by williamyang1991** [comment]
you can add 
`print(np.array(Simg).shape)` before 
`Simg = transform2(Simg).unsqueeze(dim=0)`
to see the shape of your Simg.
It should be (1024, 1024, 3)
otherwise, there is something wrong with your style image.

**Comment by hw1204** [comment]
Alpha Channel was the problem! Thanks for letting me know. One question is that input image is definitely channel 3 but Simg is channel 4...Was there a malfunction in the middle?

**Comment by williamyang1991** [comment]
My code is just read the image and transform it.
```
Simg = Image.open(os.path.join(path, filename))
Simg = transform2(Simg).unsqueeze(dim=0)
```

> It was originally a png format, but I changed it to jpg

It should be that you incorrectly changed png to jpg without discarding its alpah channel.
