### ISSUE TITLE
input must be contiguous when autograd

### ISSUE THREAD

**Issue by Sutongtong233** [williamyang1991/DualStyleGAN#39]
When I finetune DualStyleGAN, when `d_r1_loss(real_pred, real_img)`, it call 'upfirdn2d.py', and RunError:

>   File "/home/tongtong/python_project/DualStyleGAN/model/stylegan/op/upfirdn2d.py", line 143, in backward
>     ctx.out_size,
>   File "/home/tongtong/python_project/DualStyleGAN/model/stylegan/op/upfirdn2d.py", line 42, in forward
>     g_pad_y1,
> RuntimeError: input must be contiguous

I have tried to add .contiguous() after the input, but it doesn't work. What should I do?
Thanks in advance.

**Comment by williamyang1991** [comment]
I think you can follow the code in fused_act.py to modify the code of upfirdn2d.py
https://github.com/williamyang1991/DualStyleGAN/blob/fcc547c7728baffb8ddd0ce21fa0d7252d761786/model/stylegan/op/fused_act.py#L29-L31

https://github.com/williamyang1991/DualStyleGAN/blob/fcc547c7728baffb8ddd0ce21fa0d7252d761786/model/stylegan/op/fused_act.py#L49-L51

https://github.com/williamyang1991/DualStyleGAN/blob/fcc547c7728baffb8ddd0ce21fa0d7252d761786/model/stylegan/op/fused_act.py#L119

**Comment by Sutongtong233** [comment]
Thanks, the issue has been solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "williamyang1991/DualStyleGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月5日(星期五) 凌晨0:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [williamyang1991/DualStyleGAN] input must be contiguous when autograd (Issue #39)





 
I think you can follow the code in fused_act.py to modify the code of upfirdn2d.py
 https://github.com/williamyang1991/DualStyleGAN/blob/fcc547c7728baffb8ddd0ce21fa0d7252d761786/model/stylegan/op/fused_act.py#L29-L31
 
https://github.com/williamyang1991/DualStyleGAN/blob/fcc547c7728baffb8ddd0ce21fa0d7252d761786/model/stylegan/op/fused_act.py#L49-L51
 
https://github.com/williamyang1991/DualStyleGAN/blob/fcc547c7728baffb8ddd0ce21fa0d7252d761786/model/stylegan/op/fused_act.py#L119
