### ISSUE TITLE
Browse styles visually

### ISSUE THREAD

**Issue by flomerboy** [williamyang1991/DualStyleGAN#4]
Hi! 

I suspect that users trying the demo will have a magic moment when they choose a style they love, combined with an image of themselves, and then generate a pleasing image as a result. With the current slider interface for style selection, this is not really possible.
I think providing a way for users to visually browse the styles and choose one they like would help chances of this tech becoming very popular and adopted across industry.
Fantastic work!

**Comment by williamyang1991** [comment]
This is a great idea. 
Here is an overview of Cartoon dataset where images are placed in the order of their id.
You just need to sum the column number and the row number to get the id.

![cartoon_overview](https://user-images.githubusercontent.com/18130694/159848447-96fa5194-32ec-42f0-945a-3b1958bf6e5e.jpg)

Maybe @AK391 could add this overview figure to the web demo.

**Comment by flomerboy** [comment]
awesome! Thank you so much!

**Comment by AK391** [comment]
@flomerboy @williamyang1991 thanks, the demo was setup by a community member on Hugging Face https://huggingface.co/hysts, it was recently updated to add the table
