### ISSUE TITLE
prompts for the three styles generated by StableDiffusion

### ISSUE THREAD

**Issue by onion-liu** [williamyang1991/DualStyleGAN#43]
Hi, can you provide the prompts for the three styles generated by StableDiffusion?
Thanks a lot!

**Comment by williamyang1991** [comment]
I used code from https://github.com/lowfuel/progrock-stable
It provides some predefined words here https://github.com/lowfuel/progrock-stable/tree/main/settings

A ultradetailed bust portrait painting of a `<woman|man>`, highly detailed, bust portrait, a full front face in the middle of canvas, upper body, digital painting, sharp focus, `_adjective_` mood, concept art, illustration by `ARTIST`

The three datasets are generated by three `ARTIST`s

**Comment by onion-liu** [comment]
Great! Thank you so much!
