### ISSUE TITLE
why the ResBlock is added in the Discriminator rather than Generator?

### ISSUE THREAD

**Issue by wyiguanw** [williamyang1991/DualStyleGAN#44]
Thank you for this amazing work!
 I have a question about fine-tuning of the StyleGAN, which is the step 2 of Facial destylization.
![image](https://user-images.githubusercontent.com/95457754/195509787-694bc564-72e3-4dad-85e7-e48cc9339099.png)

While I reading your paper, I intuitively think that the residual path(ResBlock) are added in Generator. But, you actually added in the Discriminator. Why is that?

**Comment by williamyang1991** [comment]
We just use the official implementation of StyleGAN2

![image](https://user-images.githubusercontent.com/18130694/195512858-3dddd72f-7f0a-4005-b8b9-7b89263af43d.png)
