### ISSUE TITLE
Dataset_Preparation

### ISSUE THREAD

**Issue by Chinees-zhang** [williamyang1991/DualStyleGAN#45]
hi, there was something doubt for me that I had got only 4 face_images with a video more than 1h(109Mb). Could you please to give some suggestion?

**Comment by williamyang1991** [comment]
The face detection method is suitable for artistic portraits that look like real human faces.
Do your video's characters look very different from real face?
What your resolution of video? I only extract large faces. You can change the code:
```
if d.width() >= 256 and d.height() >= 256:
```

You can also sample more frequently
```
if i % 24 > 0: # try to find a face every 24 frames
    continue
```

**Comment by Chinees-zhang** [comment]
@williamyang1991 ，Thank you for your reply very much! Just like what you said that the video resolution is too low, and I have 
solved this issue with another video.
