### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by dongyun-kim-arch** [williamyang1991/DualStyleGAN#52]
Hello!

I am following the data preparation part to curate my own custom dataset, and I realized that face alignment and crop could be important. I saw additional files in the caricature and anime dataset such as txt file to pinpoint facial landmarks. It looks like the additional files were provided by other datasets, so I wonder if there are other tools or models I could utilize to get such additional information.

In this regard, I also wonder what preprocessing steps you used when testing the images created by Stable Diffusion.

Thank you!

**Comment by williamyang1991** [comment]
Please refer to our paper https://arxiv.org/pdf/2203.13248.pdf

A. Appendix: Implementation Details
A.1. Dataset

**Comment by dongyun-kim-arch** [comment]
Thank you for pointing it out. 
Did you manually label the landmarks of Stable Diffusion-generated images as well?
I found several open source model for facial landmarks such as YOLO, so I wonder if I could use them to get the landmarks since to get ideal performance these input settings are important.

**Comment by williamyang1991** [comment]
I follow FFHQ to detect and align the face.

**Comment by dongyun-kim-arch** [comment]
Thank you! it helps a lot!
