### ISSUE TITLE
How the identity is kept as much as possible？

### ISSUE THREAD

**Issue by JcccKing** [williamyang1991/DualStyleGAN#53]
Hello Researcher Yang.
       Thank you for your excellent work!!! I followed your training pretty well and kept my style great! But the identity and structure change a lot, do you have any better solution for the difference in identity due to PSP inverse mapping? Or which part in between you need to fine tune according to the dataset, please give me some hints, thanks!
![image](https://user-images.githubusercontent.com/46700363/202338133-6e20fbad-1fb4-4f3e-b22e-d080913194aa.png)

**Comment by williamyang1991** [comment]
- You can use a lower `--weight`. For example, `--weight 0 0 0 0 0.5 0.5 0.75 1 1 1 1 1 1 1 1 1 1 1` will only transfer colors.
- You can also perform optimization over the W+ to make better reconstruction.
- Based on your pretrained DualStyleGAN, you can also try [VToonify](https://github.com/williamyang1991/VToonify)

**Comment by JcccKing** [comment]
Hello Researcher Yang.
      Thank you very much for your prompt reply, I will try the above method and follow up by trying video style transfer. Thank you for your excellent work !!!
