### ISSUE TITLE
How to train own style with SD?

### ISSUE THREAD

**Issue by pavelxx1** [williamyang1991/DualStyleGAN#56]
Subj. Thx

**Comment by williamyang1991** [comment]
For using stablediffusion to generate style images to train DualStyleGAN,
you mey refer to https://twitter.com/ShuaiYang1991/status/1577251207155838976?s=20&t=nIOX_8SqXVvgaihTDq7L9A

**Comment by pavelxx1** [comment]
> For using stablediffusion to generate style images to train DualStyleGAN, you mey refer to https://twitter.com/ShuaiYang1991/status/1577251207155838976?s=20&t=nIOX_8SqXVvgaihTDq7L9A
thanks!👌
