### ISSUE TITLE
Could you please provide with prompts of new styles?

### ISSUE THREAD

**Issue by caopulan** [williamyang1991/DualStyleGAN#57]
Thanks a lot!

**Comment by williamyang1991** [comment]
Here https://twitter.com/ShuaiYang1991/status/1577251214470762497?s=20&t=ZNlB1jrieFekEAcD0tflTQ

'A ultradetailed bust portrait painting of a <woman|man>, highly detailed, a full front face in the middle of canvas, upper body, digital painting, sharp focus, \_adjective_ mood, illustration by \<artist>'

**Comment by caopulan** [comment]
Thanks!
