### ISSUE TITLE
Single-GPU training doesn't work well

### ISSUE THREAD

**Issue by echo1993in** [williamyang1991/DualStyleGAN#59]
In finetune_dualstylegan training ,I trained with a single GPU and  pre-trained models.I followed the instructions，but it was not well trained, and even the image collapsed.Is this because I am a single GPU and batch size is 1?
![dualstylegan-001000](https://user-images.githubusercontent.com/119465848/212606193-4a8ab741-e693-4f93-b669-9c30ba884d25.jpg)
![dualstylegan-001499](https://user-images.githubusercontent.com/119465848/212606302-b0495ab5-2035-4d4a-9794-2e070f45c30a.jpg)

**Comment by williamyang1991** [comment]
We also find it is hard to train StyleGAN/DualStyleGAN with a small batch size. 
Here is the related discussion. I think you need to tune the hyper-parameters to prevent mode collapse.

https://github.com/williamyang1991/DualStyleGAN/issues/19#issuecomment-1109899462
