### ISSUE TITLE
About train a output size of 256 dualstylegan model

### ISSUE THREAD

**Issue by echo1993in** [williamyang1991/DualStyleGAN#61]
I want to train a dualstylegan model using 256 stylegan model .I train a psp model in Z pluz and finetune stylegan in 4*8 batch in 8 GPUs. Destylizing and pretraining dualstylegan is fine.But in finetuning dualstyle ,the result is not well .I try the chageing batch size ,iters ,L2_leg_loss ,perc_loss,but it'is not work.
Is any thing wrong in training?There are some results .
![finetune-000000](https://user-images.githubusercontent.com/119465848/215371366-a19d69be-30c8-49ff-aaa9-182f8f027212.jpg)
![finetune-000600](https://user-images.githubusercontent.com/119465848/215371386-911e3641-1071-474b-99cd-4c9b62e65f5e.jpg)
I add img_gen by myself at third.
![Cartoons_00002_01](https://user-images.githubusercontent.com/119465848/215371409-79f90209-e136-4f75-b2f7-c8b4db77cc20.jpg)
![Cartoons_00011_01](https://user-images.githubusercontent.com/119465848/215371412-b6c6b5f4-3cd5-4f64-b3d4-ae5b7edc4657.jpg)
![dualstylegan-000700](https://user-images.githubusercontent.com/119465848/215371586-8ff9a43b-aa43-4ee4-be36-7c85b0f88c70.jpg)
In more than 1000 iter,the face is collapse .
![dualstylegan-001300](https://user-images.githubusercontent.com/119465848/215371607-83206c72-738c-43e4-b367-d0de9da39075.jpg)

**Comment by williamyang1991** [comment]
It seems that everything looks right before the last two steps. 

Is the penultimate image the pretrained dualstylgan's results? I think it looks like it almost tends to mode collapse (some obvious artifacts). You can use less iterations for pretraining. 

Another reason may be that the best training settings of 256 are very different from 1024. 
I haven't tried on 256. So I'm sorry that I have no idea what kinds of hyperparameters should be used. Maybe you should stop before 1000 iterations?

**Comment by echo1993in** [comment]
> It seems that everything looks right before the last two steps.
> 
> Is the penultimate image the pretrained dualstylgan's results? I think it looks like it almost tends to mode collapse (some obvious artifacts). You can use less iterations for pretraining.
> 
> Another reason may be that the best training settings of 256 are very different from 1024. I haven't tried on 256. So I'm sorry that I have no idea what kinds of hyperparameters should be used. Maybe you should stop before 1000 iterations?

The penultimate image is training at 600 iterations.  I try training illustration style ,it performs well, but not in cartoon style by the same way.

**Comment by williamyang1991** [comment]
It's true that large deformation (cartoon) is difficult to learn than small deformation (illustration).

Maybe You can use less deformed pairs to train? For example, use the psp results as the destylized faces.

![image](https://user-images.githubusercontent.com/18130694/215426567-29ae3916-7d04-4b66-90c1-bf79e5d9bd4f.png)

**Comment by echo1993in** [comment]
I trained the model  in less iterations .But the effect is more like a real person, and is not cartoon enough.
![cartoon_transfer_0_006750_0_overview](https://user-images.githubusercontent.com/119465848/215427977-d3362f60-8416-4490-8b89-22ccdc5a78e7.jpg)
![cartoon_transfer_0_019706_0_overview](https://user-images.githubusercontent.com/119465848/215427994-4c4ecfa3-4152-4dcc-9acc-f5df45a6ff94.jpg)

**Comment by williamyang1991** [comment]
https://github.com/williamyang1991/DualStyleGAN#optional-latent-optimization-and-sampling
Latent Optimization is another way to reinforce cartoon effects.
You may try it.

**Comment by echo1993in** [comment]
Thank you so much!
