### ISSUE TITLE
为什么重建的人脸跟以前相差很多呢？

### ISSUE THREAD

**Issue by seawater668** [williamyang1991/DualStyleGAN#66]
![2023-02-25 17-17-49 的屏幕截图](https://user-images.githubusercontent.com/29244715/221349203-10a0dd35-db79-4aa9-837a-490fc455259d.png)

上图中第二个图怎么重建后人眼跟原始人脸不像呢，下图中还重建出肩膀出来了，
![Image_20230225172124](https://user-images.githubusercontent.com/29244715/221349346-22734172-913a-4e37-9599-4c6da026b44e.png)
可以不用重建吗，重建主要是干什么呢？

**Comment by williamyang1991** [comment]
ReadMe里面已经解释了
![image](https://user-images.githubusercontent.com/18130694/221349700-c1265327-781c-4be5-b9ce-ffb9ab7f42b4.png)

重建是做StyleGAN inversion，将真实图片映射到StyleGAN的参数空间，然后才能对图片进行编辑和风格化
