### ISSUE TITLE
How to change weights for getting better results of style transformation ?

### ISSUE THREAD

**Issue by kasarampavan** [williamyang1991/DualStyleGAN#68]
some styles are coming fully different face, some times style only replacing with original image, how to change weights to get style transform similar to original image face

![origninal](https://user-images.githubusercontent.com/19687839/222074491-e001a9ba-02ba-4dda-97c1-3a0ad71db778.jpg)
![StyleTransformImage](https://user-images.githubusercontent.com/19687839/222074538-99d43b40-99a4-437b-a3df-fa2115fc34aa.png)
![resultImage](https://user-images.githubusercontent.com/19687839/222074579-ff050c90-0fdd-4beb-a4c5-8abdae82d0e7.png)

**Comment by williamyang1991** [comment]
Here are the supported options:

- Specify the style style with `--style` and `--style_id` 
- Specify the weight to adjust the degree of style with `--weight` (**adjust this to keep the shape**)
- Specify `--preserve_color` or set the last 11 elements of `--weight` to all zeros to preserve the color style of the content image
- Specify `--wplus` to use the original pSp encoder to extract the W+ intrinsic style code, which may better preserve the face features of the content image.

Our trained pSp encoder on Z+/W+ space cannot perfectly encode the content image. If the style transfer result more consistent with the content image is desired, one may use latent optimization to better fit the content image or using other StyleGAN encoders (as discussed in https://github.com/williamyang1991/DualStyleGAN/issues/11 and https://github.com/williamyang1991/DualStyleGAN/issues/29).

**Comment by kasarampavan** [comment]
Thank you for fast reply...
