### ISSUE TITLE
How to make toon image ,Instead of changing style transformation of original Image ?

### ISSUE THREAD

**Issue by kasarampavan** [williamyang1991/DualStyleGAN#69]
I want  to get toon image instead of changing face shape and style transform with dualstylegan model

**Comment by williamyang1991** [comment]
Here are the supported options:

Specify the style style with --style and --style_id
Specify the weight to adjust the degree of style with --weight (adjust this to keep the shape)
Specify --preserve_color or set the last 11 elements of --weight to all zeros to preserve the color style of the content image
Specify --wplus to use the original pSp encoder to extract the W+ intrinsic style code, which may better preserve the face features of the content image.
Our trained pSp encoder on Z+/W+ space cannot perfectly encode the content image. If the style transfer result more consistent with the content image is desired, one may use latent optimization to better fit the content image or using other StyleGAN encoders (as discussed in https://github.com/williamyang1991/DualStyleGAN/issues/11 and https://github.com/williamyang1991/DualStyleGAN/issues/29).

**Comment by kasarampavan** [comment]
Thank you for fast reply...
