### ISSUE TITLE
"""Add --wplus in style_transfer.py to use original w+ pSp encoder rather than z+.""" integrate in demo of Hf spaces 

### ISSUE THREAD

**Issue by Excurl** [williamyang1991/DualStyleGAN#76]
integrate w+ latent space of psp encoder in huggingface interactive demo.

**Comment by williamyang1991** [comment]
Just integrated
![image](https://user-images.githubusercontent.com/18130694/226114344-78e4fa60-6448-454d-a688-1ba12a180133.png)

**Comment by Excurl** [comment]
thanks for the reply and immediate integration..
hoping you would also integrate new Stable Diffusion pretrained models...

**Comment by williamyang1991** [comment]
I'm currently busy with another project. You can try https://huggingface.co/spaces/PKUWilliamYang/VToonify,
where we intergrate one SD model.
![image](https://user-images.githubusercontent.com/18130694/227864206-cefe6665-66b4-4327-afd6-c2d106acdf0e.png)
