### ISSUE TITLE
Toon images

### ISSUE THREAD

**Issue by Kaunain26** [williamyang1991/DualStyleGAN#77]
Hey @williamyang1991  ,

I have a question please help me,

Is it possible to cartoonize an image exactly like the image showing below. Like i want to cartoonize image similar to that one. I did not find any solution. 

![image](https://user-images.githubusercontent.com/64792378/227431580-232a09de-89cc-4f7d-b75c-3dd29c4977bf.png) ![image](https://user-images.githubusercontent.com/64792378/227431774-51ae930b-4c31-44e0-a868-2006c5c5754a.png)

DualStyleGan is used to do style transfer, But i need to do cartoonize similar to above image. 

Is It possible???  

If it's possible then how can i do it???

**Comment by williamyang1991** [comment]
DualStyleGAN learns the style from the training data.
If you want to transfer this style, you need to collection about 100 catoonized face images to train a DualStyleGAN

**Comment by Kaunain26** [comment]
Thanks for your reply. :)
