### ISSUE TITLE
 How is this picture drawn?

### ISSUE THREAD

**Issue by watertianyi** [williamyang1991/DualStyleGAN#79]
![image](https://user-images.githubusercontent.com/29244715/229012540-968a9308-8fbd-4b49-9d90-490b883ab553.png)

**Comment by williamyang1991** [comment]
Please refer to the `Style fusion` section of [inference_playground.ipynb](https://github.com/williamyang1991/DualStyleGAN/blob/main/notebooks/inference_playground.ipynb)

Once you get the fused style images, you can arrange them into a video.
