### ISSUE TITLE
pixar dataset

### ISSUE THREAD

**Issue by 41xu** [williamyang1991/DualStyleGAN#8]
Hi! Amazing work! 
I want to ask that do you mind share your pixar dataset?(not the youtube link...)

**Comment by williamyang1991** [comment]
Thank you for your interest.
The pixar dataset we used are collected from the Internet. 
Since we do not have the copyrights, we feel sorry that we cannot make this dataset public.

**Comment by zhanglonghao1992** [comment]
@williamyang1991 What about the Slamdunk dataset, would you share that dataset

**Comment by williamyang1991** [comment]
The problem is the same as the pixar dataset.
We don't have the copyrights.
