### ISSUE TITLE
finetune_stylegan.py error  - TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by tlsdmswn01** [williamyang1991/DualStyleGAN#96]
!python finetune_stylegan.py --iter 600 --batch 4 --style simpsons --augment ./data/simpsons/lmdb/ --size 256

I wrote the code like this and posted it:

Load options
ada_every: 256
ada_length: 500000
ada_target: 0.6
augment: True
augment_p: 0
batch: 4
channel_multiplier: 2
ckpt: None
d_reg_every: 16
g_reg_every: 4
iter: 600
local_rank: 0
lr: 0.002
mixing: 0.9
model_path: ./checkpoint/
n_sample: 9
path: ./data/simpsons/lmdb/
path_batch_shrink: 2
path_regularize: 2
r1: 10
save_every: 10000
size: 256
style: simpsons
wandb: False
...
    grad_input, grad_grid = GridSampleBackward.apply(grad_output, input, grid)
  File "/home/alpaco/sej/DualStyleGAN/model/stylegan/non_leaking.py", line 361, in forward
    grad_input, grad_grid = op(grad_output, input, grid, 0, 0, False)
TypeError: 'tuple' object is not callable

I keep getting this error. I followed exactly what's in the demo, but the error persists. What could be the problem? Please help.

I want to ask this in another place.

**Comment by williamyang1991** [comment]
I find a solution. You can try it.
https://github.com/williamyang1991/DualStyleGAN/issues/49#issuecomment-1492968347

**Comment by tlsdmswn01** [comment]
Thank you! 
Thanks to you, I've resolved it and am using it well!
